<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPackable>true</IsPackable>
    <PackageId>Sia.Asset</PackageId>
    <PackageDescription>Unified typed asset loading and content ownership</PackageDescription>
    <Author>Phlamcenth Sicusa</Author>
    <Company>Lunditöph Siagö</Company>
    <RepositoryUrl>https://github.com/lunditoph-siago/Sia.Engine</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Sia.Asset.Tests" />
  </ItemGroup>

</Project>
