<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPackable>true</IsPackable>
    <PackageId>Sia.Mesh</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Sia.Prelude" Version="2.1.5" />
    <PackageReference Include="Sia.Math" Version="0.0.3" />
    <PackageReference Include="Sia.CodeGenerators" Version="2.1.5" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
