using System.CodeDom.Compiler;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Sia.UI.CodeGenerators;

[Generator]
internal sealed class StaticStyleGenerator : IIncrementalGenerator
{
    internal const string InvalidStyleId = "SIAUISTYLE001";

    private const string AttributeType = "Sia.UI.StaticStyleAttribute`4";

    private static readonly SymbolDisplayFormat TypeFormat =
        SymbolDisplayFormat.FullyQualifiedFormat;

    private static readonly DiagnosticDescriptor InvalidStyle = new(
        InvalidStyleId,
        "Static styles must be top-level value types",
        "'{0}' must be a top-level, non-generic partial struct or record struct",
        "Sia.UI.Style",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly string AttributeSource = """
// <auto-generated/>
#nullable enable

namespace Sia.UI;

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sia.UI.CodeGenerators", "1.0.0")]
[global::System.AttributeUsage(
    global::System.AttributeTargets.Struct,
    Inherited = false,
    AllowMultiple = false)]
internal sealed class StaticStyleAttribute<TState, TTheme, TInteraction, TPresentation>
    : global::System.Attribute
    where TState : struct
    where TTheme : struct
    where TInteraction : struct
    where TPresentation : struct
{
}
""";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static output =>
            output.AddSource(
                "StaticStyleAttribute.g.cs",
                SourceText.From(AttributeSource, Encoding.UTF8)));

        var styles = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeType,
            static (node, _) => node is TypeDeclarationSyntax,
            static (attributeContext, _) => CreateInfo(attributeContext));
        context.RegisterSourceOutput(styles, static (output, info) =>
            Generate(output, info));
    }

    private static StyleInfo CreateInfo(GeneratorAttributeSyntaxContext context)
    {
        var style = (INamedTypeSymbol)context.TargetSymbol;
        var arguments = context.Attributes[0].AttributeClass!.TypeArguments;
        return new(style, arguments[0], arguments[1], arguments[2], arguments[3]);
    }

    private static void Generate(SourceProductionContext context, StyleInfo info)
    {
        if (!IsValid(info.Style)) {
            context.ReportDiagnostic(Diagnostic.Create(
                InvalidStyle,
                info.Style.Locations.FirstOrDefault(static location => location.IsInSource),
                info.Style.Name));
            return;
        }

        var style = TypeName(info.Style);
        var state = TypeName(info.State);
        var theme = TypeName(info.Theme);
        var interaction = TypeName(info.Interaction);
        var presentation = TypeName(info.Presentation);
        using var source = CreateSource(info.Style, out var builder);
        source.Write(Accessibility(info.Style));
        source.Write(' ');
        if (info.Style.IsReadOnly) {
            source.Write("readonly ");
        }
        source.Write(info.Style.IsRecord ? "partial record struct " : "partial struct ");
        source.Write(info.Style.Name);
        source.Write(" : global::Sia.UI.IStaticStyle<");
        WriteTypes(source, state, theme, interaction, presentation);
        source.WriteLine(">");
        source.WriteLine("{");
        source.Indent++;
        source.Write("public static global::Sia.UI.StyleBinding<");
        WriteTypes(source, style, state, theme, interaction, presentation);
        source.Write("> Bind(scoped in ");
        source.Write(state);
        source.Write(" state, global::Sia.Entity theme, global::Sia.UI.StyleLayer layer = default) => new(state, theme, layer);");
        source.WriteLine();
        source.WriteLine();
        source.Write("public sealed class Reactor : global::Sia.UI.StaticStyleReactor<");
        WriteTypes(source, style, state, theme, interaction, presentation);
        source.WriteLine(">;");
        source.Indent--;
        source.WriteLine("}");
        context.AddSource(HintName(info.Style), builder.ToString());
    }

    private static void WriteTypes(IndentedTextWriter source, params string[] types)
    {
        for (var index = 0; index < types.Length; index++) {
            if (index != 0) {
                source.Write(", ");
            }
            source.Write(types[index]);
        }
    }

    private static bool IsValid(INamedTypeSymbol style) =>
        style.TypeKind == TypeKind.Struct
        && style.ContainingType is null
        && style.TypeParameters.Length == 0
        && style.DeclaringSyntaxReferences.Any(static reference =>
            reference.GetSyntax() is TypeDeclarationSyntax syntax
            && syntax.Modifiers.Any(static modifier => modifier.ValueText == "partial"));

    private static IndentedTextWriter CreateSource(
        INamedTypeSymbol type,
        out StringBuilder builder)
    {
        builder = new StringBuilder();
        var source = new IndentedTextWriter(new StringWriter(builder), "    ");
        source.WriteLine("// <auto-generated/>");
        source.WriteLine("#nullable enable");
        source.WriteLine();
        if (!type.ContainingNamespace.IsGlobalNamespace) {
            source.Write("namespace ");
            source.Write(type.ContainingNamespace.ToDisplayString());
            source.WriteLine(";");
            source.WriteLine();
        }
        source.WriteLine("[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"Sia.UI.CodeGenerators\", \"1.0.0\")]");
        return source;
    }

    private static string TypeName(ITypeSymbol type) => type.ToDisplayString(TypeFormat);

    private static string Accessibility(INamedTypeSymbol type) =>
        type.DeclaredAccessibility == Microsoft.CodeAnalysis.Accessibility.Public
            ? "public"
            : "internal";

    private static string HintName(INamedTypeSymbol type)
    {
        var name = type.ToDisplayString();
        var builder = new StringBuilder(name.Length + 16);
        foreach (var character in name) {
            builder.Append(char.IsLetterOrDigit(character) ? character : '_');
        }
        builder.Append(".StaticStyle.g.cs");
        return builder.ToString();
    }

    private sealed record StyleInfo(
        INamedTypeSymbol Style,
        ITypeSymbol State,
        ITypeSymbol Theme,
        ITypeSymbol Interaction,
        ITypeSymbol Presentation);
}
