<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net11.0;net11.0-browser</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <IsPackable>true</IsPackable>
    <PackageId>Sia.UI</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Sia.Graphics" Version="0.0.19" />
    <PackageReference Include="Sia.RenderGraph" Version="0.0.19" />
    <PackageReference Include="Sia.WebGPU" Version="0.0.19" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Sia" Version="2.1.5" />
    <PackageReference Include="Sia.Input" Version="0.0.4" />
    <PackageReference Include="Sia.Prelude" Version="2.1.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sia.UI.CodeGenerators\Sia.UI.CodeGenerators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
    <None Include="..\Sia.UI.CodeGenerators\bin\$(Configuration)\netstandard2.0\Sia.UI.CodeGenerators.dll"
          Pack="true"
          PackagePath="analyzers/dotnet/cs"
          Visible="false" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Render/Shaders/*.wgsl" />
  </ItemGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'net11.0-browser'">
    <SupportedOSPlatformVersion>0.0</SupportedOSPlatformVersion>
  </PropertyGroup>
</Project>
