<Project>
  <PropertyGroup>
    <BistroAssetPath Condition="'$(BistroAssetPath)' == ''">$([System.IO.Path]::GetFullPath('$(BaseIntermediateOutputPath)bistro-v1/Bistro.siapbr', '$(MSBuildProjectDirectory)'))</BistroAssetPath>
    <BistroFinestAssetPath Condition="'$(BistroFinestAssetPath)' == ''">$([System.IO.Path]::GetFullPath('$(BaseIntermediateOutputPath)bistro-v1/BistroFinest.siapbr', '$(MSBuildProjectDirectory)'))</BistroFinestAssetPath>
  </PropertyGroup>

  <Target Name="PublishBistroAsset" AfterTargets="Publish">
    <DownloadFile Condition="!Exists('$(BistroAssetPath)')"
                  SourceUrl="https://github.com/lunditoph-siago/Sia.Engine/releases/download/example-assets-bistro-v1/Bistro.siapbr"
                  DestinationFolder="$([System.IO.Path]::GetDirectoryName('$(BistroAssetPath)'))"
                  DestinationFileName="$([System.IO.Path]::GetFileName('$(BistroAssetPath)'))"
                  Retries="3" RetryDelayMilliseconds="1000" />
    <VerifyFileHash File="$(BistroAssetPath)" Algorithm="SHA256"
                    Hash="26D3926FC8E5630868E484E7162F17CC8B8A67C4CCB216FDC37DCED96B199F86" />
    <DownloadFile Condition="!Exists('$(BistroFinestAssetPath)')"
                  SourceUrl="https://github.com/lunditoph-siago/Sia.Engine/releases/download/example-assets-bistro-v1/BistroFinest.siapbr"
                  DestinationFolder="$([System.IO.Path]::GetDirectoryName('$(BistroFinestAssetPath)'))"
                  DestinationFileName="$([System.IO.Path]::GetFileName('$(BistroFinestAssetPath)'))"
                  Retries="3" RetryDelayMilliseconds="1000" />
    <VerifyFileHash File="$(BistroFinestAssetPath)" Algorithm="SHA256"
                    Hash="742D432A17E1DD97F8829E531943286393EEBEBD105409B0B4547F73FBA9597C" />
    <PropertyGroup>
      <_BistroPublishPath>$([System.IO.Path]::Combine('$(PublishDir)', 'Assets', 'Bistro.siapbr'))</_BistroPublishPath>
      <_BistroPublishPath Condition="'$(RuntimeIdentifier)' == 'browser-wasm'">$([System.IO.Path]::Combine('$(PublishDir)', 'wwwroot', 'Assets', 'Bistro.siapbr'))</_BistroPublishPath>
    </PropertyGroup>
    <Copy SourceFiles="$(BistroAssetPath)" DestinationFiles="$(_BistroPublishPath)" SkipUnchangedFiles="true" />
    <Copy SourceFiles="$(BistroFinestAssetPath)" DestinationFiles="$([System.IO.Path]::GetDirectoryName('$(_BistroPublishPath)'))/BistroFinest.siapbr" SkipUnchangedFiles="true" />
  </Target>
</Project>
